Repository LunarClient/Apollo, pull requests merged in 2024-02, with the labels that each got.

#116 Improve - Add range annotations & validation
  api/src/main/java/com/lunarclient/apollo/common/icon/AdvancedResourceLocationIcon.java
  api/src/main/java/com/lunarclient/apollo/common/icon/SimpleResourceLocationIcon.java
  api/src/main/java/com/lunarclient/apollo/module/border/Border.java
  api/src/main/java/com/lunarclient/apollo/module/staffmod/StaffModModule.java
  api/src/main/java/com/lunarclient/apollo/module/team/TeamMember.java
  api/src/main/java/com/lunarclient/apollo/module/title/Title.java
  api/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModule.java
  api/src/main/java/com/lunarclient/apollo/module/transfer/PingResponse.java
  api/src/main/java/com/lunarclient/apollo/module/vignette/Vignette.java
  api/src/main/java/com/lunarclient/apollo/roundtrip/ApolloRequest.java
  api/src/main/java/com/lunarclient/apollo/stats/ApolloStats.java
  bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
  common/src/main/java/com/lunarclient/apollo/module/border/BorderModuleImpl.java
  common/src/main/java/com/lunarclient/apollo/module/title/TitleModuleImpl.java
  common/src/main/java/com/lunarclient/apollo/module/vignette/VignetteModuleImpl.java
  common/src/main/java/com/lunarclient/apollo/network/NetworkTypes.java
  common/src/main/java/com/lunarclient/apollo/util/Ranges.java
Labels: type: Enhancement

#118 Sync LunarClient Mods & Options
  api/src/main/java/com/lunarclient/apollo/mods/Mods.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModBlockOutline.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModClock.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModCps.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModDayCounter.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModMomentum.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModPackDisplay.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModPing.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModServerAddress.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModSkyblock.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModStopwatch.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModZoom.java
  docs/developers/mods/_meta.json
  docs/developers/mods/blockoutline.mdx
  docs/developers/mods/clock.mdx
  docs/developers/mods/cps.mdx
  docs/developers/mods/daycounter.mdx
  docs/developers/mods/momentum.mdx
  docs/developers/mods/packdisplay.mdx
  docs/developers/mods/ping.mdx
  docs/developers/mods/serveraddress.mdx
  docs/developers/mods/skyblock.mdx
  docs/developers/mods/stopwatch.mdx
  docs/developers/mods/zoom.mdx
Labels: type: Enhancement

#119 Bump Apollo to 1.0.9
  bukkit-example/src/main/resources/plugin.yml
  bukkit/src/platform-loader/resources/plugin.yml
  bungee/src/platform-loader/resources/plugin.yml
  deploy.sh
  gradle.properties
  velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
Labels: type: Enhancement

#124 Update event listener example
  bukkit-example/src/main/java/com/lunarclient/apollo/example/listeners/GeneralListenerExample.java
  docs/developers/events.mdx
Labels: type: Documentation

#123 Disable Packet Enrichment module by default
  api/src/main/java/com/lunarclient/apollo/module/ApolloModule.java
  api/src/main/java/com/lunarclient/apollo/module/packetenrichment/PacketEnrichmentModule.java
  common/src/main/java/com/lunarclient/apollo/module/ApolloModuleManagerImpl.java
  docs/developers/modules/packetenrichment.mdx
Labels: type: Enhancement

#122 Allow releases on version branches
  .github/workflows/deploy.yml
Labels: type: Enhancement

#126 Bump to 1.1.0
  bukkit-example/src/main/resources/plugin.yml
  bukkit/src/platform-loader/resources/plugin.yml
  bungee/src/platform-loader/resources/plugin.yml
  deploy.sh
  gradle.properties
  velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
Labels: type: Enhancement

#127 Version - 1.1.0
  .github/workflows/deploy.yml
  api/src/main/java/com/lunarclient/apollo/module/ApolloModule.java
  api/src/main/java/com/lunarclient/apollo/module/packetenrichment/PacketEnrichmentModule.java
  api/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModule.java
  bukkit-example/src/main/java/com/lunarclient/apollo/example/listeners/GeneralListenerExample.java
  bukkit-example/src/main/resources/plugin.yml
  bukkit/build.gradle.kts
  bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
  bukkit/src/platform-loader/resources/plugin.yml
  bungee/src/platform-loader/resources/plugin.yml
  common/src/main/java/com/lunarclient/apollo/module/ApolloModuleManagerImpl.java
  deploy.sh
  docs/developers/events.mdx
  docs/developers/modules/packetenrichment.mdx
  docs/developers/modules/tntcountdown.mdx
  docs/developers/utilities/icons.mdx
  gradle.properties
  velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
Labels: type: Enhancement

#128 Fix - GitHub Release using the wrong commit
  .github/workflows/deploy.yml
Labels: type: Bug
