Repository LunarClient/Apollo, pull requests merged in 2024-08, with the labels that each got.

#162 Lightweight
  deploy.sh
  docs/developers/modules/glint.mdx
  docs/internals/lightweight.mdx
Labels: type: Documentation, type: Enhancement

#161 fix: ClassCastException for Color conversion in newer Java versions
  common/src/main/java/com/lunarclient/apollo/option/OptionsImpl.java
Labels: status: Accepted, type: Bug

#163 Feature - Make `ApolloPlayer` an `Audience`
  api/src/main/java/com/lunarclient/apollo/player/ApolloPlayer.java
  bukkit/build.gradle.kts
  bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
  bukkit/src/main/java/com/lunarclient/apollo/wrapper/BukkitApolloPlayer.java
  bungee/build.gradle.kts
  bungee/src/main/java/com/lunarclient/apollo/ApolloBungeePlatform.java
  bungee/src/main/java/com/lunarclient/apollo/wrapper/BungeeApolloPlayer.java
  gradle/libs.versions.toml
  velocity/src/main/java/com/lunarclient/apollo/wrapper/VelocityApolloPlayer.java
Labels: type: Enhancement
