Repository LunarClient/Apollo, pull requests merged in 2024-05, with the labels that each got.

#149 Fix - TNT Countdown Module on 1.20.5+
  bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
Labels: type: Bug

#150 Feature - Glint Module
  docs/developers/modules/_meta.json
  docs/developers/modules/glint.mdx
Labels: type: Enhancement

#151 Add showcase image to module overviews
  docs/developers/modules/beam.mdx
  docs/developers/modules/chat.mdx
  docs/developers/modules/coloredfire.mdx
  docs/developers/modules/cooldown.mdx
  docs/developers/modules/glow.mdx
  docs/developers/modules/limb.mdx
  docs/developers/modules/modsetting.mdx
  docs/developers/modules/nametag.mdx
  docs/developers/modules/notification.mdx
  docs/developers/modules/richpresence.mdx
  docs/developers/modules/saturation.mdx
  docs/developers/modules/staffmod.mdx
  docs/developers/modules/stopwatch.mdx
  docs/developers/modules/team.mdx
  docs/developers/modules/transfer.mdx
  docs/developers/modules/waypoint.mdx
Labels: type: Documentation

#153 Sync LunarClient Mods & Options
  api/src/main/java/com/lunarclient/apollo/mods/Mods.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModClock.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModPing.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModTitles.java
  docs/developers/mods/clock.mdx
  docs/developers/mods/ping.mdx
  docs/developers/mods/titles.mdx
Labels: type: Enhancement

#152 Bump to 1.1.3
  bukkit-example/src/main/resources/plugin.yml
  bukkit/src/platform-loader/resources/plugin.yml
  bungee/src/platform-loader/resources/plugin.yml
  deploy.sh
  gradle.properties
  velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
Labels: type: Enhancement

#154 Version - 1.1.3
  api/src/main/java/com/lunarclient/apollo/mods/Mods.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModChat.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModClock.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModMemory.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModPing.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModSkyblock.java
  api/src/main/java/com/lunarclient/apollo/mods/impl/ModTitles.java
  bukkit-example/src/main/resources/plugin.yml
  bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
  bukkit/src/platform-loader/resources/plugin.yml
  bungee/src/platform-loader/resources/plugin.yml
  deploy.sh
  docs/developers/mods/chat.mdx
  docs/developers/mods/clock.mdx
  docs/developers/mods/memory.mdx
  docs/developers/mods/ping.mdx
  docs/developers/mods/skyblock.mdx
  docs/developers/mods/titles.mdx
  docs/developers/modules/_meta.json
  docs/developers/modules/beam.mdx
  docs/developers/modules/chat.mdx
  docs/developers/modules/coloredfire.mdx
  docs/developers/modules/cooldown.mdx
  docs/developers/modules/glint.mdx
  docs/developers/modules/glow.mdx
  docs/developers/modules/limb.mdx
  docs/developers/modules/modsetting.mdx
  docs/developers/modules/nametag.mdx
  docs/developers/modules/notification.mdx
  docs/developers/modules/richpresence.mdx
  docs/developers/modules/saturation.mdx
  docs/developers/modules/staffmod.mdx
  docs/developers/modules/stopwatch.mdx
  docs/developers/modules/team.mdx
  docs/developers/modules/transfer.mdx
  docs/developers/modules/waypoint.mdx
  gradle.properties
  velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
Labels: type: Enhancement
